{
 "title": "SensorPush-Dotnet",
 "time": { "from": "2025-11-15T05:00:00.000Z", "to": "2025-11-17T04:59:59.000Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sensors",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"sensor_name\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_sensor_name",
     "groupBy": [
      { "params": [ "sensor_name" ], "type": "tag" }
     ],
     "measurement": "SensorPush",
     "query": "from(bucket: \"sensorpush_dotnet\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SensorPush\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=~", "value": "/^$sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "$tag_sensor_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorPush",
     "query": "from(bucket: \"sensorpush_dotnet\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SensorPush\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=~", "value": "/^$sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "$tag_sensor_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorPush",
     "query": "from(bucket: \"sensorpush_dotnet\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SensorPush\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dewpoint\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=~", "value": "/^$sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_sensor_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorPush",
     "query": "from(bucket: \"sensorpush_dotnet\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SensorPush\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=~", "value": "/^$sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "VPD",
   "type": "timeseries",
   "description": "Vapor Pressure Deficit",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "alias": "$tag_sensor_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorPush",
     "query": "from(bucket: \"sensorpush_dotnet\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SensorPush\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vpd\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "vpd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=~", "value": "/^$sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "$tag_sensor_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorPush_V",
     "query": "from(bucket: \"sensorpush_dotnet\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SensorPush_V\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=~", "value": "/^$sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "description": "This plot shows always the last Voltage value which has been reported to the cloud!",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_sensor_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorPush_V",
     "query": "from(bucket: \"sensorpush_dotnet\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SensorPush_V\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=~", "value": "/^$sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "alias": "$tag_sensor_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorPush",
     "query": "from(bucket: \"sensorpush_dotnet\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SensorPush\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=~", "value": "/^$sensors$/" }
     ]
    }
   ]
  }
 ]
}